import type { AccountOrder, AccountUser, SavedAddress, WishlistItem } from "@/types/account";

export const MOCK_ACCOUNT_USER: AccountUser = {
  name: "সাব্বির আহমেদ",
  phone: "০১৭১২৩৪৫৬৭৮",
  email: "sabbir.ahmed@example.com",
  memberSince: "জানুয়ারি ২০২৪ থেকে সদস্য",
  initials: "সা",
};

export const MOCK_ACCOUNT_ORDERS: AccountOrder[] = [
  {
    id: "#FB-10482",
    date: "১৮ জুলাই, ২০২৬",
    item: "প্রিমিয়াম স্লিম ফিট শার্ট ও আরও ১টি",
    itemCount: 2,
    total: "৳ ২,৮৮০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10436",
    date: "০৯ জুলাই, ২০২৬",
    item: "লেদার ফরমাল লোফার",
    itemCount: 1,
    total: "৳ ২,৭৯০",
    status: "পথে আছে",
    statusTone: "sale",
  },
  {
    id: "#FB-10391",
    date: "২৮ জুন, ২০২৬",
    item: "অর্গানিক কটন টি-শার্ট",
    itemCount: 1,
    total: "৳ ৮৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
];

export const MOCK_ALL_ORDERS: AccountOrder[] = [
  {
    id: "#FB-10482",
    date: "১৮ জুলাই, ২০২৬",
    item: "প্রিমিয়াম স্লিম ফিট শার্ট ও আরও ১টি",
    itemCount: 2,
    total: "৳ ২,৮৮০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10436",
    date: "০৯ জুলাই, ২০২৬",
    item: "লেদার ফরমাল লোফার",
    itemCount: 1,
    total: "৳ ২,৭৯০",
    status: "পথে আছে",
    statusTone: "sale",
  },
  {
    id: "#FB-10391",
    date: "২৮ জুন, ২০২৬",
    item: "অর্গানিক কটন টি-শার্ট",
    itemCount: 1,
    total: "৳ ৮৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10344",
    date: "১৫ জুন, ২০২৬",
    item: "কটন চেক লুঙ্গি (দুটি)",
    itemCount: 2,
    total: "৳ ১,৩৮০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10297",
    date: "০৩ জুন, ২০২৬",
    item: "ডেনিম জিন্স প্যান্ট",
    itemCount: 1,
    total: "৳ ১,৯৫০",
    status: "বাতিল হয়েছে",
    statusTone: "muted",
  },
  {
    id: "#FB-10251",
    date: "২২ মে, ২০২৬",
    item: "পাঞ্জাবি সেট ও আরও ২টি",
    itemCount: 3,
    total: "৳ ৩,৬৫০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
];

export const MOCK_SAVED_ADDRESSES: SavedAddress[] = [
  {
    id: "home",
    label: "বাসার ঠিকানা",
    recipient: "সাব্বির আহমেদ",
    phone: "০১৭১২৩৪৫৬৭৮",
    address: "বাড়ি ১২, রোড ৫, ধানমন্ডি, ঢাকা ১২০৯",
    isDefault: true,
  },
  {
    id: "office",
    label: "অফিস",
    recipient: "সাব্বির আহমেদ",
    phone: "০১৭১২৩৪৫৬৭৮",
    address: "লেভেল ৬, গুলশান অ্যাভিনিউ, ঢাকা ১২১২",
  },
  {
    id: "parents",
    label: "মা-বাবার বাড়ি",
    recipient: "আহমেদ সাহেব",
    phone: "০১৮৫৫৬৬৭৭৮৮",
    address: "গ্রাম: কালিগঞ্জ, থানা: গাজীপুর সদর, গাজীপুর ১৭০০",
  },
];

export const MOCK_WISHLIST_ITEMS: WishlistItem[] = [
  {
    id: "wl1",
    name: "প্রিমিয়াম স্লিম ফিট শার্ট",
    price: "৳ ১,৪৫০",
    originalPrice: "৳ ২,১০০",
    discount: "৩১%",
    category: "শার্ট",
    inStock: true,
    initial: "শ",
  },
  {
    id: "wl2",
    name: "লেদার ফরমাল লোফার",
    price: "৳ ২,৭৯০",
    originalPrice: "৳ ৩,৫০০",
    discount: "২০%",
    category: "জুতা",
    inStock: true,
    initial: "জ",
  },
  {
    id: "wl3",
    name: "অর্গানিক কটন টি-শার্ট",
    price: "৳ ৮৯০",
    category: "টি-শার্ট",
    inStock: false,
    initial: "ট",
  },
  {
    id: "wl4",
    name: "ব্লক প্রিন্ট কুর্তা",
    price: "৳ ১,৯৫০",
    originalPrice: "৳ ২,৪০০",
    discount: "১৯%",
    category: "কুর্তা",
    inStock: true,
    initial: "ক",
  },
  {
    id: "wl5",
    name: "ডেনিম জিন্স প্যান্ট",
    price: "৳ ১,৮৫০",
    category: "প্যান্ট",
    inStock: true,
    initial: "প",
  },
  {
    id: "wl6",
    name: "ফ্লোরাল সামার ড্রেস",
    price: "৳ ২,২৫০",
    originalPrice: "৳ ২,৮০০",
    discount: "২০%",
    category: "ড্রেস",
    inStock: false,
    initial: "ড",
  },
];
