import type {
  AdminProduct,
  AdminOrder,
  AdminCategory,
  AdminCustomer,
  AdminRecentOrder,
  AdminLowStockItem,
  AdminStatCard,
} from "@/types/admin";

export const ADMIN_STAT_CARDS: AdminStatCard[] = [
  {
    label: "মোট আয়",
    value: "৳ ৪,৮৬,৩৫০",
    sub: "এই মাসে +১২%",
    tone: "brand",
  },
  {
    label: "মোট অর্ডার",
    value: "১,২৪৮",
    sub: "এই মাসে ৮৬টি নতুন",
    tone: "sale",
  },
  {
    label: "মোট পণ্য",
    value: "৩৪৬",
    sub: "১২টি স্টক শেষ",
    tone: "brand",
  },
  {
    label: "মোট কাস্টমার",
    value: "৫,৭৩২",
    sub: "এই মাসে ২১৪ জন নতুন",
    tone: "brand",
  },
];

export const ADMIN_RECENT_ORDERS: AdminRecentOrder[] = [
  {
    id: "#FB-10520",
    customer: "রাহেলা বেগম",
    total: "৳ ২,৪৫০",
    status: "প্রক্রিয়াধীন",
    statusTone: "sale",
  },
  {
    id: "#FB-10519",
    customer: "করিম উদ্দিন",
    total: "৳ ১,৮৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10518",
    customer: "নাজনীন আক্তার",
    total: "৳ ৩,৩৪০",
    status: "পথে আছে",
    statusTone: "sale",
  },
  {
    id: "#FB-10517",
    customer: "মিজানুর রহমান",
    total: "৳ ৯৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
  },
  {
    id: "#FB-10516",
    customer: "সুমাইয়া খানম",
    total: "৳ ৪,১২০",
    status: "বাতিল হয়েছে",
    statusTone: "muted",
  },
];

export const ADMIN_LOW_STOCK: AdminLowStockItem[] = [
  { id: "ls1", name: "প্রিমিয়াম স্লিম ফিট শার্ট (M)", stock: 3, initial: "শ" },
  { id: "ls2", name: "লেদার ফরমাল লোফার (৪২)", stock: 2, initial: "জ" },
  { id: "ls3", name: "ব্লক প্রিন্ট কুর্তা (L)", stock: 1, initial: "ক" },
  { id: "ls4", name: "ডেনিম জিন্স প্যান্ট (৩২)", stock: 4, initial: "প" },
];

export const ADMIN_PRODUCTS: AdminProduct[] = [
  {
    id: "p1",
    name: "প্রিমিয়াম স্লিম ফিট শার্ট",
    category: "শার্ট",
    price: "৳ ১,৪৫০",
    stock: 48,
    status: "active",
    initial: "শ",
  },
  {
    id: "p2",
    name: "লেদার ফরমাল লোফার",
    category: "জুতা",
    price: "৳ ২,৭৯০",
    stock: 22,
    status: "active",
    initial: "জ",
  },
  {
    id: "p3",
    name: "অর্গানিক কটন টি-শার্ট",
    category: "টি-শার্ট",
    price: "৳ ৮৯০",
    stock: 0,
    status: "out_of_stock",
    initial: "ট",
  },
  {
    id: "p4",
    name: "ব্লক প্রিন্ট কুর্তা",
    category: "কুর্তা",
    price: "৳ ১,৯৫০",
    stock: 15,
    status: "active",
    initial: "ক",
  },
  {
    id: "p5",
    name: "ডেনিম জিন্স প্যান্ট",
    category: "প্যান্ট",
    price: "৳ ১,৮৫০",
    stock: 34,
    status: "active",
    initial: "প",
  },
  {
    id: "p6",
    name: "ফ্লোরাল সামার ড্রেস",
    category: "ড্রেস",
    price: "৳ ২,২৫০",
    stock: 0,
    status: "out_of_stock",
    initial: "ড",
  },
  {
    id: "p7",
    name: "কটন চেক লুঙ্গি",
    category: "লুঙ্গি",
    price: "৳ ৬৯০",
    stock: 80,
    status: "active",
    initial: "ল",
  },
  {
    id: "p8",
    name: "পাঞ্জাবি (এমব্রয়ডারি)",
    category: "পাঞ্জাবি",
    price: "৳ ২,৪৯০",
    stock: 12,
    status: "inactive",
    initial: "পা",
  },
  {
    id: "p9",
    name: "স্পোর্টস ট্র্যাকস্যুট",
    category: "স্পোর্টস",
    price: "৳ ১,৬৯০",
    stock: 27,
    status: "active",
    initial: "স্",
  },
  {
    id: "p10",
    name: "ক্যাজুয়াল স্নিকার্স",
    category: "জুতা",
    price: "৳ ১,৯৫০",
    stock: 19,
    status: "active",
    initial: "স্ন",
  },
];

export const ADMIN_ORDERS: AdminOrder[] = [
  {
    id: "#FB-10520",
    customer: "রাহেলা বেগম",
    date: "২৫ জুলাই, ২০২৬",
    items: 2,
    total: "৳ ২,৪৫০",
    status: "প্রক্রিয়াধীন",
    statusTone: "sale",
    phone: "০১৮১২৩৪৫৬৭৮",
  },
  {
    id: "#FB-10519",
    customer: "করিম উদ্দিন",
    date: "২৪ জুলাই, ২০২৬",
    items: 1,
    total: "৳ ১,৮৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
    phone: "০১৭৩৩৪৪৫৫৬৬",
  },
  {
    id: "#FB-10518",
    customer: "নাজনীন আক্তার",
    date: "২৩ জুলাই, ২০২৬",
    items: 3,
    total: "৳ ৩,৩৪০",
    status: "পথে আছে",
    statusTone: "sale",
    phone: "০১৬১৯৮৭৬৫৪৩",
  },
  {
    id: "#FB-10517",
    customer: "মিজানুর রহমান",
    date: "২২ জুলাই, ২০২৬",
    items: 1,
    total: "৳ ৯৯০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
    phone: "০১৫৫৪৪৩৩২২১",
  },
  {
    id: "#FB-10516",
    customer: "সুমাইয়া খানম",
    date: "২১ জুলাই, ২০২৬",
    items: 4,
    total: "৳ ৪,১২০",
    status: "বাতিল হয়েছে",
    statusTone: "muted",
    phone: "০১৯০০৯৮৭৬৫৪",
  },
  {
    id: "#FB-10515",
    customer: "আরিফ হোসেন",
    date: "২০ জুলাই, ২০২৬",
    items: 2,
    total: "৳ ২,৮৮০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
    phone: "০১৭৮৮৯৯০০১১",
  },
  {
    id: "#FB-10514",
    customer: "সানিয়া ইসলাম",
    date: "১৯ জুলাই, ২০২৬",
    items: 1,
    total: "৳ ১,৪৫০",
    status: "প্রক্রিয়াধীন",
    statusTone: "sale",
    phone: "০১৮৫৬৭৮৯০১২",
  },
  {
    id: "#FB-10513",
    customer: "জাহাঙ্গীর আলম",
    date: "১৮ জুলাই, ২০২৬",
    items: 5,
    total: "৳ ৬,৫৫০",
    status: "ডেলিভারি হয়েছে",
    statusTone: "brand",
    phone: "০১৭২২৩৩৪৪৫৫",
  },
];

export const ADMIN_CATEGORIES: AdminCategory[] = [
  { id: "c1", name: "শার্ট", slug: "shirt", productCount: 42, status: "active", initial: "শ" },
  { id: "c2", name: "পাঞ্জাবি", slug: "panjabi", productCount: 28, status: "active", initial: "পা" },
  { id: "c3", name: "টি-শার্ট", slug: "t-shirt", productCount: 56, status: "active", initial: "ট" },
  { id: "c4", name: "প্যান্ট", slug: "pants", productCount: 38, status: "active", initial: "প" },
  { id: "c5", name: "জুতা", slug: "shoes", productCount: 34, status: "active", initial: "জ" },
  { id: "c6", name: "ড্রেস", slug: "dress", productCount: 22, status: "inactive", initial: "ড" },
  { id: "c7", name: "কুর্তা", slug: "kurta", productCount: 18, status: "active", initial: "ক" },
  { id: "c8", name: "লুঙ্গি", slug: "lungi", productCount: 15, status: "active", initial: "ল" },
];

export const ADMIN_CUSTOMERS: AdminCustomer[] = [
  {
    id: "cu1",
    name: "রাহেলা বেগম",
    phone: "০১৮১২৩৪৫৬৭৮",
    email: "rahela@example.com",
    orders: 8,
    totalSpent: "৳ ১২,৪৫০",
    joinDate: "মার্চ ২০২৫",
    initial: "রা",
  },
  {
    id: "cu2",
    name: "করিম উদ্দিন",
    phone: "০১৭৩৩৪৪৫৫৬৬",
    email: "karim@example.com",
    orders: 5,
    totalSpent: "৳ ৮,৯৫০",
    joinDate: "জুন ২০২৫",
    initial: "ক",
  },
  {
    id: "cu3",
    name: "নাজনীন আক্তার",
    phone: "০১৬১৯৮৭৬৫৪৩",
    email: "naznin@example.com",
    orders: 12,
    totalSpent: "৳ ২১,৩৪০",
    joinDate: "জানুয়ারি ২০২৫",
    initial: "না",
  },
];

export const PRODUCT_STATUS_LABELS: Record<AdminProduct["status"], string> = {
  active: "সক্রিয়",
  inactive: "নিষ্ক্রিয়",
  out_of_stock: "স্টক শেষ",
};

export const CATEGORY_FILTER_OPTIONS = [
  { value: "all", label: "সব ক্যাটাগরি" },
  { value: "শার্ট", label: "শার্ট" },
  { value: "পাঞ্জাবি", label: "পাঞ্জাবি" },
  { value: "টি-শার্ট", label: "টি-শার্ট" },
  { value: "প্যান্ট", label: "প্যান্ট" },
  { value: "জুতা", label: "জুতা" },
  { value: "ড্রেস", label: "ড্রেস" },
  { value: "কুর্তা", label: "কুর্তা" },
  { value: "লুঙ্গি", label: "লুঙ্গি" },
];

export const PRODUCT_STATUS_FILTER_OPTIONS = [
  { value: "all", label: "সব স্ট্যাটাস" },
  { value: "active", label: "সক্রিয়" },
  { value: "inactive", label: "নিষ্ক্রিয়" },
  { value: "out_of_stock", label: "স্টক শেষ" },
];

export const ORDER_STATUS_FILTER_OPTIONS = [
  { value: "all", label: "সব স্ট্যাটাস" },
  { value: "প্রক্রিয়াধীন", label: "প্রক্রিয়াধীন" },
  { value: "পথে আছে", label: "পথে আছে" },
  { value: "ডেলিভারি হয়েছে", label: "ডেলিভারি হয়েছে" },
  { value: "বাতিল হয়েছে", label: "বাতিল হয়েছে" },
];
